version: '3.5'

services:
  laravel:
    build:
      context: '.'
    volumes:
      - .:/var/www/html
      - ./../repositories:/var/www/html/packages
    ports:
      - 8000:80
  
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672

networks:
  default:
    external:
      name: microservices-network

