version: '3.5'

services:
  laravel:
    build:
      context: '.'
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80

  pgsql:
    image: postgres:9.5
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=laravel
      - POSTGRES_USER=laravel
      - POSTGRES_PASSWORD=secret

  phppgadmin:
    image: neimheadh/phppgadmin:latest
    ports:
      - '8888:80'
    environment:
      - POSTGRES_HOST=pgsql
      - POSTGRES_PORT=5432
      - POSTGRES_USER=laravel
      - POSTGRES_PASS=secret
    depends_on:
      - pgsql
  
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./docker/mongo:/data/db
    environment:
      MONGO_INITDB_DATABASE: database
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
    links:
      - mongo
  
  redis:
    build:
      context: ./redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/redis:/data
    ports:
      - '6379:6379'
  
  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672


